name = "sveltekit-shopify"
compatibility_date = "2024-05-27"
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[env.preview.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"